# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
